interface Api {
  base: string;
  getDashboard: string;
  getAccountsDashboard: string
  getMySensors: string;
  getSensors: string;
  getAggregate3Days: string;
  getTempSensors: string;
  addSensors: string;
  getContacts: string;
  getContact: string;
  getOrders: string;
  getOrder: string;
  getLocationsByContact: string;
  getPersonalContacts: string;
  addPersonalContact: string;
  getBusinessContacts: string;
  getBusinessContactDetail: string;
  addBusinessContactLink: string;
  deleteBusinessContactLink: string;
  addBusinessContact: string;
  getAlgorandAccounts: string;
  getSensorsOwners: string;
  promoteSensor: string;
  addOwnerPersonalDeviceLink: string;
  addOwnerBusinessDeviceLink: string;
  deleteOwnerPersonalDeviceLink: string;
  deleteOwnerBusinessDeviceLink: string;
  addInfrastructurePersonalDeviceLink: string;
  addInfrastructureBusinessDeviceLink: string;
  deleteInfrastructurePersonalDeviceLink: string;
  deleteInfrastructureBusinessDeviceLink: string;
  getKycInfos: string;
  initKycAccount: string;
  getBetatesters: string;
  addBetatester: string;
  fixPin: string;
  addOrder: string;
  getSensorFEHistory: string;
  getSensorsFE: string;
  getPurchasesCounts: string;
  getProductTypes: string;
  getPaymentTypes: string;
  addOrderFull: string;
  updateOrderFull: string;
  getExportOrders: string;
  deleteOrder: string;
  deleteDeviceOwner: string;
  getLicenses: string;
  freeLicense: string;
  changeAccount: string;
  moveNfts: string;
  nftMove: string;
  changeMail: string;
  changeMailOrder: string;
  downloadZipInvoice: string;
  clawback: string;
  changeMailSensor: string;
  getTransactions: string;
  updateTransaction: string,
  trackTransaction: string,
  exportTransaction: string,
  getSyncOrders: string,
  saveSyncOrders: string,
  banDevice: string,
  banMail: string,
  addContact: string,
  getLicensesHistory: string,
  getSensorsLicensesReport: string,
  totalTransactions: string,
  mergeContact: string,
  refreshKycOnboarding: string,
  checkData: string;
}

export default Api;